### ISSUE TITLE
Create an issue here if you are facing any problem while using the script.

### ISSUE THREAD

**Issue by A-Unix** [A-Unix/Cartoonize#1]

**Comment by A-Unix** [comment]
I'm just re-opening it so that I can keep an eye. :)

**Comment by Mregy1** [comment]
Hi, 
Every time i try to install it i get this : Checking if the script is running as root!
This script must be run as root. Please use 'sudo' along with the command or login as root user.

I am running it on Windows 10
What shall I do?

**Comment by A-Unix** [comment]
> Hi, 
> Every time i try to install it i get this : Checking if the script is running as root!
> This script must be run as root. Please use 'sudo' along with the command or login as root user.
> 
> I am running it on Windows 10
> What shall I do?

Try running it on a linux distro!

**Comment by Mregy1** [comment]
So, it won't be compatible with windows by any means?

**Comment by A-Unix** [comment]
> So, it won't be compatible with windows by any means?

I didn't meant that, if you can install python in your system, then you can definitely run this script on windows as well, however, the commands I have provided in README.md won't apply on windows, so I advice you to do your own research on how to run the script on windows, try googling it or finding videos on youtube. Good luck 🤞

**Comment by Mregy1** [comment]
thnx for your time
